### ISSUE TITLE
Handle Komorebi app rules rename

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#1040]
https://github.com/LGUG2Z/komorebi/commit/b32bef7c8e38668fedda64ae042ec3d5eeba6ac9 heads up that float_identifiers will probably be renamed to ignore_identifiers as part of some ongoing work to make a distinction between completely ignored hwnds and managed-but-floating hwnds

Komorebi added a backwards-compat alias to ensure that float_identifiers can still be used upstream for a version or two, not sure if this is something you can also do to ensure forward-compat for ignore_identifiers

**Comment by urob** [comment]
Feel free to assign me on this one
