### ISSUE TITLE
bug: Closing Whim.Runner from task manager hides windows in other workspaces

### ISSUE THREAD

**Issue by dinesh-58** [dalyIsaac/Whim#1087]
Steps to recreate:

- Launch Whim
- open a few windows in different workspaces
- kill Whim.Runner using task manager

Doing so hides windows that were not in the current workspace when killing Whim, with no way to access them. These are shown in the task manager but not in the taskbar. Closing using `whim.core.exit_whim` doesn't have this issue

**Comment by dalyIsaac** [comment]
Unfortunately, this is expected behaviour. Whim manually changes the visibility of windows, and when it's killed from the task manager there's nothing it can do. 

Is there a specific scenario in why you want to kill Whim like this?
