### ISSUE TITLE
Sticky monitor workspaces

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#660]
The sticky monitor workspaces plugin (name TBD) should:

- [x] Contain a list of workspaces assigned to a monitor
- [x] Expose commands `focus_next_workspace_on_current_monitor` + `*_previous_*`, to activate the next/previous workspace in that monitor's list
- [x] The existing `focus_workspace` commands would continue to do the same as they do now, but would **move workspaces across monitors**
  - The plugin would update the monitor object that keeps track of which workspace is on which monitor whenever a workspace is moved ( workspaces can only be assigned to a single monitor at a time)
- [x] Config option that lets users configure which workspaces are assigned to which monitor on startup

## Follow-on tickets

- [x] Provide a variant of the `WorkspaceWidget` for the bar that only lists the currently active workspaces on each monitor.

---

### Core

- [x] Create a mechanism to map monitors to their index
  - [x] If a monitor doesn't exist, release all workspaces
- [x] Add to `MapSector`
- [x] Add last activated monitor (index?) to `Workspace`
- [x] Update workspace creation
- [x] Workspace activation
  - [x] 1. Try activate on the current monitor
  - [x] 2. Try activate on the last monitor
  - [x] 3. Activate on the first available monitor
- [x] Automatically create workspaces if none are available for a monitor
- [x] Save state
- [x] Docs
- [x] Tests

### Commands

- [x] `focus_next_workspace_on_current_monitor` + `*_previous_*`, to activate the next/previous workspace in that monitor's list
- [x] `move_window_to_[next|previous]_workspace_on_monitor`
- [x] TODOs
- [x] Docs
- [x] Tests

### YAML

- [x] Update schema.json
- [x] Parse `monitors` and pass to workspace creation
- [x] Docs
- [x] TODOs
- [x] Tests

### Bar

- [x] Update existing widget to only show workspaces which can run on a given monitor
- [x] TODOs
- [x] Tests

**Comment by urob** [comment]
Having `move_window_to_[next|previous]_workspace_on_monitor` commands would also work great with this (i.e, the sticky-monitor variant of https://github.com/dalyIsaac/Whim/issues/659).

**Comment by Gorgeous-Goose** [comment]
Imo this is a necessary feature, and the only reason (besides lack of documentation on certain things) someone would want to use any other tiling manager over Whim.

Having to press a hotkey to swap to the correct monitor before pulling up a workspace means you have to track state (where your focus is, what monitor you're on) vs. instantly doing what you want.

Changing the focus command to 'reassign'  the monitor its associated with also sounds great and convenient.

**Comment by urob** [comment]
Could the two yaml approaches be reconciled by making `workspaces` in the alternate approach a list & by making `monitors` an optional argument that defaults to `all`?

```yaml
workspaces:
  - name: Browser # available everywhere if monitors is not specified
  - name: Slack
  - name Code     # only available on monitor 1
    monitors: [1] 
  - name: YouTube # available on monitor 1 and 2
    monitors: [1, 2] 
```

**Comment by dalyIsaac** [comment]
I like that approach - I'll give it a shot and see how it goes

**Comment by dalyIsaac** [comment]
Functionality added in:

- #1071
- #1072
- #1073
- #1074
