### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#671]
- [x] Remove padding around icon: 
    ![Image](https://user-images.githubusercontent.com/17995621/265548851-06b8db8e-efd9-4ae9-8b48-591c45b1a17c.png)
- [ ] Alternative icon idea: little white puffy cloud in a blue sky

---

- [ ] Taskbar
- [ ] Search
- [ ] Start

**Comment by urob** [comment]
We should just use the official icon for Win 11, it clearly says that it is intended to be used with a tiling WM :wink:

<img src="https://github.com/dalyIsaac/Whim/assets/978080/81fcb12d-5138-47e0-847f-b8c7ac3ed6e2" width=100 />

Joke aside, I like the current icon (without padding)

**Comment by dalyIsaac** [comment]
https://www.figma.com/file/Hg9xSUVo8BQDu9wQdvo0pl/Whim-Icon?type=design&node-id=0%3A1&mode=design&t=4AY0ADLZhhMlx1oO-1
