### ISSUE TITLE
New matching strategies for auto-app-rules

### ISSUE THREAD

**Issue by urob** [dalyIsaac/Whim#685]
Komorebi is preparing to add new `matching strategies` to their application-specific-configuration repository.
https://github.com/LGUG2Z/komorebi-application-specific-configuration/issues/56

Currently, the `auto-app-rules` script only support `equals` and `legacy` and raises an error on  all other matching strategies.

- [ ]  Add dummy `MatchingStrategy` class that can support different matching strategies for each kind. Do not raise on `not implemented` -- @urob
- [ ] Implement the `MatchingStrategies` that can be implemented with the existing `filterManager` commands. Make sure `Legacy` maps to correct strategy depending on `kind` [(see here)](https://github.com/LGUG2Z/komorebi/blob/ddfcf8b76ffb0fdc7888eaba9c6dcf22ca5603c0/komorebi/src/window.rs#L561-L577) -- @urob 
    - for `Class` and `Exe`: `[Legacy, Equals]`
    -  for `Title`: `[Legacy, Equals, StartsWith, EndsWith, Contains]`
 - [ ] #690
 - [ ] Add new `filterManager` commands to support more matching strategies for `Class` and `Exe`. Do this only if/when they are used by komorebi? -- @dalyIsaac and @urob

**Comment by dalyIsaac** [comment]
> Add new `filterManager` commands to support more matching strategies for `Class` and `Exe`. Do this only if/when they are used by komorebi? -- @dalyIsaac and @urob

`IFilterManager` already supports adding an arbitrary `Filter` lambda function, so we can do things like:

```csharp
filterManager.Add((window) => window.ProcessFileName.StartsWith("C:\\Program Files\\WindowsApps\\Microsoft.WindowsCalculator_"));

```

https://github.com/dalyIsaac/Whim/blob/1b1daececd3dfecf1b141146b05ab7098274b571/src/Whim/Router/IFilterManager.cs#L5-L19

---

> Look into how to convert Rust regex expressions to C# and add Regex matching for Title

Conversion sounds like a hard computer science problem. I wonder if it'd be easier to use C# FFI to bind to a Rust function which takes the Rust regex.

**Comment by dalyIsaac** [comment]
There's also some strange behavior with the placement of the comments in the generated source code - see https://github.com/dalyIsaac/Whim/pull/686/files

**Comment by urob** [comment]
> There's also some strange behavior with the placement of the comments in the generated source code - see https://github.com/dalyIsaac/Whim/pull/686/files

Those are actually as intended. The first one is a typo on the Komorebi-side [see here](https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/361c969423b4fdfde29609db02201df2cf97a08d/applications.yaml#L1-L4). The other ones are rule-comments.

The general pattern is:
```
AppName
appRule 1 // rule-comment if exists
appRule 2

NextAppName
```

**Comment by urob** [comment]
> `IFilterManager` already supports adding an arbitrary `Filter` lambda function, so we can do things like:
> 
> ```cs
> filterManager.Add((window) => window.ProcessFileName.StartsWith("C:\\Program Files\\WindowsApps\\Microsoft.WindowsCalculator_"));
> ```

Would there be any concern about performance if we'd set up all rules using the general `Filter`? Specifically, what's the performance of looking up `_filters.Any(f => f(window));` vs checking membership in `_ignore*`? 

If there are no concerns for performance, using the general filter would be very clean code-wise, at least for `Equals`, `StartsWith`, `EndsWith` and `Contains`.

**Comment by urob** [comment]
Also, does `window.ProcessFileName` really incude the full path? I did a quick test and the following seems to work:
```
context.FilterManager.Add((window) => window.ProcessFileName.StartsWith("firefox.exe"));
```

**Comment by dalyIsaac** [comment]
> Would there be any concern about performance if we'd set up all rules using the general `Filter`? Specifically, what's the performance of looking up `_filters.Any(f => f(window));` vs checking membership in `_ignore*`?
>
> If there are no concerns for performance, using the general filter would be very clean code-wise, at least for `Equals`, `StartsWith`, `EndsWith` and `Contains`.

It's `O(n)` lookup, so it's slower than `O(1)` lookup for the equality checks

I think for now it's fine. If it does become a problem, we can look at some fancy data structures like tries?

**Comment by dalyIsaac** [comment]
> Also, does `window.ProcessFileName` really incude the full path? 

Yeah, that was my bad, I meant `window.ProcessFilePath`.

**Comment by urob** [comment]
> Conversion sounds like a hard computer science problem. I wonder if it'd be easier to use C# FFI to bind to a Rust function which takes the Rust regex.

I just pushed a PR addressing the first 3 issues here. I left the implementation of the `Regex` matching strategy open for a later point. It's pretty low priority given that there are currently no Komorebi app rules utilizing it.

**Comment by dalyIsaac** [comment]
I left one comment on the PR - I miscommunicated one thing.
