### ISSUE TITLE
Add ability to remove all keybinds

### ISSUE THREAD

**Issue by gplusplus314** [dalyIsaac/Whim#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Proposal

This is useful for people who have muscle memory with other tilers, or otherwise benefit from starting from scratch. Instead of calling `context.KeybindManager.Remove(...)` for every single default, it would be nice to simply just blast everything away in one shot.

### Alternatives

I did consider adding a way to enumerate commands, which would then let you iteratively `Remove()` all of them, but I felt like that would be overkill.

### Additional context

Workspacer, which Whim is inspired by, has the `UnsubscribeAll` method that essentially does the same thing.

**Comment by dalyIsaac** [comment]
Closed as part of #688
