### ISSUE TITLE
Window disappears when set to floating

### ISSUE THREAD

**Issue by urob** [dalyIsaac/Whim#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Behavior

I encountered an issue where windows "disappear" when set to floating. Based on `Window Spy`, it seems they are pushed outside the workspace boundaries when floating is toggled on:

**Active Window Position (docked):**
```
Screen:	x: 3839	y: 50	w: 3842	h: 2111
Client:	x: 3850	y: 52	w: 3820	h: 2098
```

**Active Window Position (floating):**
```
Screen:	x: 7679	y: 58	w: 3826	h: 2095
Client:	x: 7690	y: 60	w: 3804	h: 2082
```

### Config

```csharp
https://github.com/urob/whim-config/blob/cb2b95e524dc1177efe62a75cdfde89f6b1a6910/whim.config.csx
```

### Environment

Can add if needed

### Steps To Reproduce

I am not sure yet. This isn't always the case. However, once a window is affected, it will reliably disappear when tiling is toggled on. In this case, it was `OneNote` which is affected

**Comment by dalyIsaac** [comment]
Hmm, I haven't been able to reproduce this. Do you have any debug logs which might help debug this?
