### ISSUE TITLE
Refactor remaining `[Next|Previous]` method pairs?

### ISSUE THREAD

**Issue by urob** [dalyIsaac/Whim#734]
Just did a quick pattern search to identify the remaining `Next`/`Previous` method pairs. These two would fit the `Adjacent` pattern well:
- `WorkspaceManager.MoveWindowTo[Next|Previous]Monitor`
- `MonitorManager.Get[Next|Previous]Monitor`

This one also lends itself to a merge, but the `Adjacent` naming seems slightly less fitting:
- `Workspace.[Next|Previous]LayoutEngine`

**Comment by dalyIsaac** [comment]
Will be replaced with the updated structure in #890
