### ISSUE TITLE
Fix #796

### ISSUE THREAD

**Issue by urob** [dalyIsaac/Whim#804]
`Workspace.TrySetLayoutEngineFromIndex()` got broken by #796

- Changing layouts won't take effect until another event triggers `DoLayout`
- Also affects various subsidiary methods: `TrySetLayoutEngineFromName`, `CycleLayoutEngine`, `ActivatePreviouslyActiveLayoutEngine`

**Comment by dalyIsaac** [comment]
I have reconsidered #796.

Methods which should be (mostly) internal-only will not call `DoLayout`:

- [x] `AddWindow`
- [x] `RemoveWindow`
- [x] `MinimizeWindowStart`
- [x] `MinimizeWindowEnd`

Methods which are typically called in isolation will now call `DoLayout` again, with a parameter to defer `DoLayout`:

- [ ] `FocusLastFocusedWindow`
- [ ] `FocusWindowInDirection`
- [ ] `SwapWindowInDirection`
- [ ] `MoveWindowEdgesInDirection`
- [ ] `MoveWindowToPoint`

The `PerformCustomLayoutEngineAction` methods will:

- [ ] Call `DoLayout`
- [ ] Include a property in `LayoutEngineCustomAction` to defer `DoLayout`

**Comment by dalyIsaac** [comment]
My intention was to not always trigger `DoLayout` for internal calls as there were some unnecessary calls. In retrospect I was overzealous with it, as you'd expect something to happen when you call `SwapWindowInDirection`.

It's not user error - more a helpful point of view from a user 😄.
