### ISSUE TITLE
Bar Height does not work

### ISSUE THREAD

**Issue by markox92** [dalyIsaac/Whim#884]
I have created empty bar to check what is wrong, there is some minimum of Bar Height or not?

Whether I set the height to 16 or 30, the result appears the same; however, setting it to 150 shows a noticeable difference.
   
bar.resources.xaml

    <Style x:Key="bar:height" TargetType="RelativePanel">
        <Setter Property="Height" Value="16" />
    </Style>

whim.config.csx

    string file = context.FileManager.GetWhimFileDir("bar.resources.xaml");
    context.ResourceManager.AddUserDictionary(file);
    // Left components
    List<BarComponent> leftComponents = new()
    {
        //ActiveLayoutWidget.CreateComponent(),
        //WorkspaceWidget.CreateComponent()
    };

    // Center components
        List<BarComponent> centerComponents = new()
    {
        //FocusedWindowWidget.CreateComponent()
    };
    // Right components
    List<BarComponent> rightComponents  = new()
    {
        //DateTimeWidget.CreateComponent(60*1000, "h:mm tt")
    };

    BarConfig barConfig = new(leftComponents, centerComponents, rightComponents);
    BarPlugin barPlugin = new(context, barConfig);
    context.PluginManager.AddPlugin(barPlugin);

**Comment by urob** [comment]
This is just a wild guess, but this might be related to both 16 and 30 being less than the minimum height on your computer. The minimum height can vary depending on various configuration settings, including this one: https://github.com/dalyIsaac/Whim/issues/730#issuecomment-1863761492.

Related, on some computers, a binding minimum height results in cropping, while on others it results in the bar height being set to the minimum height.

**Comment by markox92** [comment]
But I have using default scaling and default font size on Windows 11, resolution 1920x1080 monitor and this bar looks very big, for this configuration they should be something around 20,24px for best result :(

**Comment by urob** [comment]
> But I have using default scaling and default font size on Windows 11, resolution 1920x1080 monitor and this bar looks very big, for this configuration they should be something around 20,24px for best result :(

Are you using the default style sheet for the bar otherwise? If the whole bar scales too big, you could also try reducing the font size, padding and margin.

**Comment by markox92** [comment]
Padding and margins is set to 0, font size is really small but looks that font size does not affect this problem, like is there is some minimum height is set of 30px and bar won't go smaller.

**Comment by urob** [comment]
> Padding and margins is set to 0, font size is really small but looks that font size does not affect this problem, like is there is some minimum height is set of 30px and bar won't go smaller.

If you link your resources file, I can take a look.

**Comment by markox92** [comment]
Yes, I can
https://gist.github.com/markox92/b994b49da5fa381b160dd8126de32b71

But also here is what happened without resources loaded.


https://github.com/dalyIsaac/Whim/assets/159203552/f4b17b38-e2fe-4f37-8165-bd5836944d88

**Comment by urob** [comment]
> Yes, I can https://gist.github.com/markox92/b994b49da5fa381b160dd8126de32b71
> 

Can you try this one:

```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
 <Style x:Key="bar:height" TargetType="RelativePanel">
        <Setter Property="Height" Value="8" />
    </Style>

    <!--  Shared text block style  -->
    <Style x:Key="_base:text_block" TargetType="TextBlock">
        <Setter Property="Margin" Value="0" />
        <Setter Property="Padding" Value="0" />
        <Setter Property="FontSize" Value="2" />
    </Style>

    <!--  Shared button style  -->
    <Style x:Key="_base:button" TargetType="Button">
        <Setter Property="Margin" Value="0" />
        <Setter Property="Padding" Value="0" />
        <Setter Property="BorderThickness" Value="0" />
        <Setter Property="FontSize" Value="2" />
    </Style>

    <!--  Root panel  -->
    <Style x:Key="bar:root_panel" TargetType="RelativePanel">
        <Setter Property="Margin" Value="0" />
        <Setter Property="Padding" Value="0" />
    </Style>

    <StaticResource x:Key="bar:active_layout:button" ResourceKey="_base:button" />
    <StaticResource x:Key="bar:tree_layout:button" ResourceKey="_base:button" />
    <StaticResource x:Key="bar:workspace:button" ResourceKey="_base:button" />
    <StaticResource x:Key="bar:focused_window:text_block" ResourceKey="_base:text_block" />
    <StaticResource x:Key="bar:date_time:text_block" ResourceKey="_base:text_block" />

</ResourceDictionary>
```

**Comment by markox92** [comment]
Same, right you can see date and time with fonst size 2

![Screenshot 2024-04-28 212817](https://github.com/dalyIsaac/Whim/assets/159203552/3ef19a8b-a0c9-499e-9b49-8b83a2922701)

**Comment by urob** [comment]
Thanks for checking. I tried setting my display to your resolution and scaling, and on my side the bar shrinks as expected. So this confirms that it is behaving differently on different systems.

To further debug, it would be useful if we could pinpoint what configuration setting in our System is making the difference. Unfortunately, I don't have a good guess at the moment.

@dalyIsaac if you have a moment, could you also try load the above resource from your user config? I may misremember, but I vaguely recollect that you were also experiencing a minimum height issue at some point, whereas I for the same configuration saw the bar cropping content. Maybe this is related?

**Comment by markox92** [comment]
There is a serious problem here with scaling. Check this. 


https://github.com/dalyIsaac/Whim/assets/159203552/d865869f-ba9f-4825-938c-3b618a132987

**Comment by markox92** [comment]
Update, if I set custom scale 100% does not work, but if I set custom scale 101,102,103... in that case is working fine... so scale 100% is problem there...

**Comment by urob** [comment]
That's super useful! I think @dalyIsaac is also using 100% scaling, so that lines up. Not sure right now whether that's something going wrong on the whim-side or on the xaml-side. Isaac, do you have a hunch?

In the meantime, is there any drawback to setting the scale to 101%? We should probably add a note to the docs, maybe with a suggestion how to workaround the issue until we find a proper fix.

**Comment by dalyIsaac** [comment]
> Whether I set the height to 16 or 30, the result appears the same; however, setting it to 150 shows a noticeable difference.

This issue may be that there's (confusingly) two ways to set the bar height:

1. The height specified in XAML, which is the height of the element.
2. The height specified in the `BarConfig`, which is the height of the window - see [`BarConfig.Height`](https://dalyisaac.github.io/Whim/api/Whim.Bar.BarConfig.html?q=barconfig#Whim_Bar_BarConfig_Height).

> Update, if I set custom scale 100% does not work, but if I set custom scale 101,102,103... in that case is working fine... so scale 100% is problem there...

I'm not sure what the reason behind this - dealing with Windows scaling has been somewhat painful.

Using the config you linked in https://github.com/dalyIsaac/Whim/issues/884#issuecomment-2081599105 and updating the `BarConfig.Height` in addition to the XAML had a more sane scaling.

Hopefully this helps 🤞

**Comment by markox92** [comment]
I will test this in the Beta and Dev channels to check if there is anything wrong with Windows. A simple fix is to disable scaling bar in Whim

**Comment by urob** [comment]
> This issue may be that there's (confusingly) two ways to set the bar height:
> 
>     1. The height specified in XAML, which is the height of the element.
> 
>     2. The height specified in the `BarConfig`, which is the height of the window - see [`BarConfig.Height`](https://dalyisaac.github.io/Whim/api/Whim.Bar.BarConfig.html?q=barconfig#Whim_Bar_BarConfig_Height).
> 

One clarifications regarding the two settings:

They are both doing the same thing. The `bar:height` xaml property isn't used anywhere on the xaml side. The only thing that it does is to define a parseable property that we read on the Whim side to set `BarConfig._height` if not explicitly specified by the user in their `csx` using `BarConfig`. 

> Using the config you linked in https://github.com/dalyIsaac/Whim/issues/884#issuecomment-2081599105 and updating the `BarConfig.Height` in addition to the XAML had a more sane scaling.

Normally, one should only need to use one or the other. Note though that `BarConfig` [takes precedence](https://github.com/dalyIsaac/Whim/blob/2062e05ff1af54444997482aa4c7daab2507805c/src/Whim.Bar/BarConfig.cs#L41-L55), so changing the resource property isn't expected to do anything if `BarConfig.Height` is set.

**Comment by markox92** [comment]
> I will test this in the Beta and Dev channels to check if there is anything wrong with Windows. A simple fix is to disable scaling bar in Whim

Ok same things on Beta and Dev.

Anyway, I have checked the size in pixels of this bar, so when I start Whim, whatever the height I have in the config, the bar is always 39px. But if I change the scaling and switch it back to default (100%), I get a bar that is 16px as I defined in the config.

I have checked this code and can't understand, 39px has no logic.

**Comment by dalyIsaac** [comment]
> They are both doing the same thing. The `bar:height` xaml property isn't used anywhere on the xaml side. The only thing that it does is to define a parseable property that [we read on the Whim side](https://github.com/dalyIsaac/Whim/blob/2062e05ff1af54444997482aa4c7daab2507805c/src/Whim.Bar/BarConfig.cs#L41-L55) to set `BarConfig._height` if not explicitly specified by the user in their `csx` using `BarConfig.Height`.

I stand corrected 😄 

> Ok same things on Beta and Dev.

This doesn't surprise me - window scaling behavior has changed quite a bit over the different Windows versions and APIs.

> Anyway, I have checked the size in pixels of this bar, so when I start Whim, whatever the height I have in the config, the bar is always 39px. 

Just to confirm, setting `BarConfig.Height` itself doesn't do anything?

> But if I change the scaling and switch it back to default (100%), I get a 16px bar as I defined in the config.

This does actually ring a bell. There is some weird chicanery to deal with monitors which have monitors of different scaling, but that case is when there are

**Comment by dalyIsaac** [comment]
In #886 I've updated how bar windows positions are set - they now use the workaround I mentioned for monitors with non-100% scaling. For some reason I haven't looked into yet, it appears that you have to set `BarConfig.Height` instead of the XAML height (I might've missed something as it was a quick fix).

If it doesn't work, let me know and I'll take deeper look.

**Comment by Gorgeous-Goose** [comment]
The .height works correctly now, but the font doesn't rescale to match (text gets cut off). I put in urob's bar.resources.xaml in the .whim folder but it doesn't appear to be doing anything.

**Comment by urob** [comment]
> The .height works correctly now, but the font doesn't rescale to match (text gets cut off). 

The font doesn't scale automatically, you'll have to manually configure it (via `bar.recources.xaml` to match the bar height). 

> I put in urob's bar.resources.xaml in the .whim folder but it doesn't appear to be doing anything. 

Did you tell Whim to use it in your `csx`?

> Would be nice if Whim just checked the font sizes and made sure they are at most equal to or -1 of bar height (could factor in margins as well).

We could try to do something like this eventually. But it's a bit tricky given that the font rendering depends on various OS settings like display scale and font accessibility scale. More importantly, the "max font size" also depends on various properties like margin, padding, border sizes, etc. Given that those can be freely styled in the xaml file, it's hard to predict from the Whim-side how that affects the bar spacing without knowing what style properties the user ends up using. One may consider this a downside of giving full flexibility to the user to style the bar via a xaml-stylesheet, though I would consider it a feature.
